### ISSUE TITLE
Separate out decision GFX

### ISSUE THREAD

**Issue by Zankoas** [Kaiserreich/Kaiserreich-4-GFX-Search#1]
Decision GFX come in two types; small icons like this:
![decision_cat_communard_flag](https://user-images.githubusercontent.com/24595951/79911025-978dfa80-8417-11ea-8e2f-faec9f2b07aa.png)

And larger category GFX like this:
![decision_cat_generic_swi_new_order](https://user-images.githubusercontent.com/24595951/79911057-a2488f80-8417-11ea-89ae-36ca99fa23bd.png)

Splitting them into two groups would be of great help. The fill for them isn't currently split, but easy to do.

**Comment by Yard1** [comment]
Done in c4224d2cbe4d3f3ef89f322060e459b05f8555a5

**Comment by Zankoas** [comment]
Was split into three in the end, with category icons and decision icons separate, in addition to category  pictures being separate; even better!
